"""
pack_verify.py
Verification Tool: Validates Python Unpacking Logic.
"""

import numpy as np
import torch
import os
import sys

# Import the unpacking logic from train.py
from train import unpack_batch_to_tensors, PACKED_DTYPE
# Constants
from model import NUM_INPUT_PLANES, NUM_INPUT_SCALARS, BOARD_AREA, POLICY_OUTPUT_SIZE

def verify():
    print("--- Starting Verification ---")

    # 1. Load Ground Truth (The raw floats generated by C++)
    print("Loading Ground Truth files...")
    truth_planes = np.fromfile("test_truth_planes.bin", dtype=np.float32)
    truth_scalars = np.fromfile("test_truth_scalars.bin", dtype=np.float32)
    truth_policy = np.fromfile("test_truth_policy.bin", dtype=np.float32)
    truth_value_abs = np.fromfile("test_truth_value.bin", dtype=np.float32)

    # Sanity check file sizes
    expected_planes = NUM_INPUT_PLANES * BOARD_AREA
    if truth_planes.size != expected_planes:
        print(f"Error: test_truth_planes.bin has {truth_planes.size} floats, expected {expected_planes}.")
        sys.exit(1)
        
    expected_scalars = NUM_INPUT_SCALARS
    if truth_scalars.size != expected_scalars:
        print(f"Error: test_truth_scalars.bin has {truth_scalars.size} floats, expected {expected_scalars}.")
        sys.exit(1)

    # 2. Load Packed Data
    print("Loading Packed Binary...")
    raw_packed = np.fromfile("test_packed.bin", dtype=PACKED_DTYPE)
    
    if len(raw_packed) == 0:
        print("Error: Packed file is empty!")
        sys.exit(1)

    # 3. Perform Unpacking
    print("Unpacking...")
    # NOTE: Function now returns (planes, scalars, policy, value, mask)
    unpacked_planes, unpacked_scalars, unpacked_policy, unpacked_value, _ = unpack_batch_to_tensors(raw_packed)

    # --- 4. PREPARE COMPARISON ---
    # The NN expects everything in RELATIVE order.
    # C++ board_to_tensors already does this for Planes and Scalars.
    # But our test_truth_value.bin was saved in ABSOLUTE order.
    
    cp = raw_packed['current_player'][0]
    print(f"Current Player detected as: {cp}")

    # Re-order the Truth Value to be Relative [CP, CP+1, CP+2, CP+3] % 4
    rel_indices = (int(cp) + np.arange(4)) % 4
    truth_value_rel = torch.from_numpy(truth_value_abs[rel_indices]).view(1, 4)

    truth_planes = torch.from_numpy(truth_planes).view(1, NUM_INPUT_PLANES, 8, 8)
    truth_scalars = torch.from_numpy(truth_scalars).view(1, NUM_INPUT_SCALARS)
    truth_policy = torch.from_numpy(truth_policy).view(1, POLICY_OUTPUT_SIZE)

    # 5. Compare
    print("\n--- Comparison Results ---")
    
    # A. Compare Value
    if torch.allclose(truth_value_rel, unpacked_value, atol=1e-5):
        print("✅ VALUES Match (Correctly Relative)")
    else:
        print("❌ VALUES Mismatch")
        print(f"Truth (Relative): {truth_value_rel}")
        print(f"Unpacked:         {unpacked_value}")

    # B. Compare Policy
    if torch.allclose(truth_policy, unpacked_policy, atol=1e-5):
        print("✅ POLICY Matches")
    else:
        print("❌ POLICY Mismatch")

    # C. Compare Spatial Planes
    if torch.allclose(truth_planes, unpacked_planes, atol=1e-5):
        print("✅ SPATIAL PLANES Match")
    else:
        print("❌ SPATIAL PLANES Mismatch")
        for ch in range(NUM_INPUT_PLANES):
            if not torch.allclose(truth_planes[0, ch], unpacked_planes[0, ch], atol=1e-5):
                print(f"  -> Mismatch at Plane {ch}")

    # D. Compare Scalars
    if torch.allclose(truth_scalars, unpacked_scalars, atol=1e-5):
        print("✅ SCALARS Match")
    else:
        print("❌ SCALARS Mismatch")
        # Print first few mismatches
        diff = torch.abs(truth_scalars - unpacked_scalars)
        # Check indices of mismatch
        idx = torch.nonzero(diff > 1e-5, as_tuple=True)[1]
        for i in idx:
            print(f"  -> Mismatch at Scalar {i}: Truth={truth_scalars[0,i]:.4f}, Unpacked={unpacked_scalars[0,i]:.4f}")

if __name__ == "__main__":
    if not os.path.exists("test_packed.bin"):
        print("Error: test_packed.bin not found. Run pack_test_gen first.")
    else:
        verify()