"""
pack_verify.py
Verification Tool: Validates Python Unpacking Logic.
"""

import numpy as np
import torch
import os
import sys

# Import the unpacking logic from train.py
from train import unpack_batch_to_tensors, PACKED_DTYPE

# Constants
NN_INPUT_CHANNELS = 62 
BOARD_AREA = 64
POLICY_SIZE = 4096
VALUE_SIZE = 4

def verify():
    print("--- Starting Verification ---")

    # 1. Load Ground Truth (The raw floats generated by C++)
    print("Loading Ground Truth files...")
    truth_input = np.fromfile("test_truth_input.bin", dtype=np.float32)
    truth_policy = np.fromfile("test_truth_policy.bin", dtype=np.float32)
    truth_value_abs = np.fromfile("test_truth_value.bin", dtype=np.float32)

    # Sanity check file size
    expected_floats = NN_INPUT_CHANNELS * 8 * 8
    if truth_input.size != expected_floats:
        print(f"Error: test_truth_input.bin has {truth_input.size} floats, expected {expected_floats} (for {NN_INPUT_CHANNELS} channels).")
        print("Did you forget to rebuild 'pack_test_gen' or update 'types.h'?")
        sys.exit(1)

    # 2. Load Packed Data
    print("Loading Packed Binary...")
    raw_packed = np.fromfile("test_packed.bin", dtype=PACKED_DTYPE)
    
    if len(raw_packed) == 0:
        print("Error: Packed file is empty!")
        sys.exit(1)

    # 3. Perform Unpacking
    print("Unpacking...")
    # NOTE: Function now returns legal_mask as 4th value
    unpacked_input, unpacked_policy, unpacked_value, _ = unpack_batch_to_tensors(raw_packed)

    # --- 4. PREPARE COMPARISON ---
    # The NN expects everything in RELATIVE order.
    # C++ board_to_floats_into already does this for Input and Policy.
    # But our test_truth_value.bin was saved in ABSOLUTE order.
    
    cp = raw_packed['current_player'][0]
    print(f"Current Player detected as: {cp}")

    # Re-order the Truth Value to be Relative [CP, CP+1, CP+2, CP+3] % 4
    rel_indices = (int(cp) + np.arange(4)) % 4
    truth_value_rel = torch.from_numpy(truth_value_abs[rel_indices]).view(1, 4)

    truth_input = torch.from_numpy(truth_input).view(1, NN_INPUT_CHANNELS, 8, 8)
    truth_policy = torch.from_numpy(truth_policy).view(1, POLICY_SIZE)

    # 5. Compare
    print("\n--- Comparison Results ---")
    
    # A. Compare Value
    if torch.allclose(truth_value_rel, unpacked_value, atol=1e-5):
        print("✅ VALUES Match (Correctly Relative)")
    else:
        print("❌ VALUES Mismatch")
        print(f"Truth (Relative): {truth_value_rel}")
        print(f"Unpacked:         {unpacked_value}")

    # B. Compare Policy
    if torch.allclose(truth_policy, unpacked_policy, atol=1e-5):
        print("✅ POLICY Matches")
    else:
        print("❌ POLICY Mismatch")

    # C. Compare Input State
    if torch.allclose(truth_input, unpacked_input, atol=1e-5):
        print("✅ INPUT STATE Matches")
    else:
        print("❌ INPUT STATE Mismatch")
        for ch in range(NN_INPUT_CHANNELS):
            if not torch.allclose(truth_input[0, ch], unpacked_input[0, ch], atol=1e-5):
                print(f"  -> Mismatch at Channel {ch}")

if __name__ == "__main__":
    if not os.path.exists("test_packed.bin"):
        print("Error: test_packed.bin not found. Run pack_test_gen first.")
    else:
        verify()